export const INITIAL_LOAD = "INITIAL_LOAD";
export const GET_FOODLIST_SUCCESS = "GET_FOODLIST_SUCCESS";
export const GET_FOODLIST_FAILURE = "GET_FOODLIST_FAILURE";



export const GET_EMPLOYEELIST_SUCCESS = "GET_EMPLOYEELIST_SUCCESS";
export const GET_EMPLOYEELIST_FAILURE = "GET_EMPLOYEELIST_FAILURE";